services:
  db:
    image: postgres:15
    container_name: hockey_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hockey-network

  api:
    build: ./backend
    container_name: hockey_api
    env_file:
      - .env  # ðŸ‘ˆ Cambiado a la raÃ­z
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hockey-network

  frontend:
    build: ./frontend
    container_name: hockey_frontend
    env_file:
      - .env  # ðŸ‘ˆ Cambiado a la raÃ­z
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - hockey-network

volumes:
  postgres_data:

networks:
  hockey-network:
    driver: bridge