services:
  db:
    image: postgres:15
    container_name: hockey_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    networks:
      - hockey-network

  api:
    build: ./backend
    container_name: hockey_api
    env_file:
      - .env
    # Quitamos ports públicos, Nginx llegará por la red interna
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hockey-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: hockey_frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Quitamos ports públicos
    expose:
      - "5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - hockey-network

  nginx:
    image: nginx:alpine
    container_name: hockey_proxy
    ports:
      - "80:80" # EL ÚNICO PUERTO ABIERTO AL MUNDO
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api
    networks:
      - hockey-network

volumes:
  postgres_data:

networks:
  hockey-network:
    driver: bridge